name: Daily Weather Update

on:
  schedule: 
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run incremental ETL script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd src
          python extract_incremental.py